/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.ContatoDao;
import Model.Contato;
import Model.TContato;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Andeson
 */
public class FormContato extends javax.swing.JDialog {

    private Contato cadastro;
    private ContatoDao dados;

    /**
     * Creates new form FormContato
     */
    public FormContato(java.awt.Frame parent, Contato contato, ContatoDao pacote) {
        super(parent, true);
        initComponents();
        setSize(400, 150);
        this.cadastro = contato;
        this.dados = pacote;
        setLocationRelativeTo(parent);

        cbTipo.setModel(new DefaultComboBoxModel(TContato.values()));

        if (this.cadastro == null) {
            this.cadastro = new Contato();
        } else {
            edContato.setText(this.cadastro.getNome());
            edTelefone.setText(this.cadastro.getTelefone());
            cbTipo.setSelectedItem(this.cadastro.getTipo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        edContato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        btnCancela = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contato");
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Nome do Contato");
        getContentPane().add(jLabel1);
        getContentPane().add(edContato);

        jLabel3.setText("Telefone ");
        getContentPane().add(jLabel3);
        getContentPane().add(edTelefone);

        jLabel4.setText("Tipo do Contato");
        getContentPane().add(jLabel4);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbTipo);

        btnCancela.setText("Cancelar");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancela);

        btnSalva.setText("Salvar");
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalva);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        // TODO add your handling code here:

        if (edContato.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Informe o nome do contato!");
            return;
        }

        if (edTelefone.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Informe o núm. do telefone do contato!");
            return;
        }

        this.cadastro.setNome(edContato.getText());
        this.cadastro.setTelefone(edTelefone.getText());
        this.cadastro.setTipo((TContato) cbTipo.getSelectedItem());

        try {

            if (this.cadastro.getId() == 0) {
                dados.Inserir(cadastro);
            } else {
                dados.Alterar(cadastro);
            }
            
            dispose();
        } catch (Exception e) {
            System.out.println("Erro no manipular dados.");
            System.err.println(e.getMessage());
        }

    }//GEN-LAST:event_btnSalvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnSalva;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JTextField edContato;
    private javax.swing.JTextField edTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
