/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * James, Enock, Mateus  1.0
 *
 * Rodrigo, fox, Gustavo CExpre, claudinei.  0.3
 */
package registros;

import java.util.Random;

/**
 *
 * @author Andeson
 */
public class FormTela extends javax.swing.JFrame {

    /**
     * Creates new form FormTela
     */
    public FormTela() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGeraDados = new javax.swing.JButton();
        edReg = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        lbNum = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGeraDados.setText("Gerar Registros");
        btnGeraDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraDadosActionPerformed(evt);
            }
        });

        edReg.setModel(new javax.swing.SpinnerNumberModel(100, null, 1410065407, 1));

        jLabel1.setText("Número de Registros");

        lbNum.setText("jLabel2");

        jButton2.setText("Consultar número de registros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edReg, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGeraDados)
                            .addComponent(jButton2))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeraDados))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNum)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeraDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraDadosActionPerformed
        // TODO add your handling code here:

        new Thread() {
            @Override
            public void run() {
                btnGeraDados.setEnabled(false);
                BancoDeDados d = new BancoDeDados();

                int total = (int) edReg.getValue();
                String nomes[] = {"JOÃO", "MARIA", "JOSÉ", "JOAQUINA", "MARTA",
                    "MENEZES", "JESUS", "SILVA", "ANTONIA", "ANA", "FRANCISCO",
                    "RAFAEL", "MIGUEL", "ENOCK", "JAMES", "IGOR", "TIAGO",
                    "LARISA", "BERNADO", "TAYNA", "CASTRO", "SANTES", "MONEIRO",
                    "JUNIOR", "CLAUDINEI", "BONERGES", "FOX", "FERNANDO",
                    "EVERALDO", "CERRADO"};

                Random indice = new Random();
                Random valors = new Random();
                Random ativos = new Random();
                String nome;
                for (int i = 1; i <= total; i++) {

                    nome = nomes[indice.nextInt(nomes.length)] + " "
                            + nomes[indice.nextInt(nomes.length)] + " DE "
                            + nomes[indice.nextInt(nomes.length)];
                    
                    d.InsertTabela(nome, (valors.nextFloat() * i), ativos.nextBoolean(), i);

                    System.out.println("nome: " + nome);
                }
                btnGeraDados.setEnabled(true);
            }

        }.start();


    }//GEN-LAST:event_btnGeraDadosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        new Thread() {
//            @Override
//            public void run() {
                //com Thread
//                BancoDeDados d = new BancoDeDados();
//                lbNum.setText(d.getNum());
//
//            }
//        }.start();

        //sem Thread
        BancoDeDados d = new BancoDeDados();
        lbNum.setText(d.getNum());

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeraDados;
    private javax.swing.JSpinner edReg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbNum;
    // End of variables declaration//GEN-END:variables
}
